mysql:
  host: "example.com"
  port: 3306
  username: "username"
  password: "password"
  database: "minecraft"
  table: "playerLevel"
message:
  syncError: "Couln't sync your experience"
  dbError: "An error occured while trying to save your experience to database"